on:
  push:
    branches:
      - main

name: ðŸš€ Deploy website on push

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploying
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Getting the latest code
        uses: actions/checkout@v3

      - name: ðŸ“‚ Sync
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.uoemcu.co.ke
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /portal.uoemcu.co.ke/

      - name: Install Composer Dependencies
        run: composer update

      - name: Install NPM Packages
        run: npm install
